# Wrangler configuration for OAuth Workers
name = "retain-flow-oauth"
main = "workers/oauth-google.js"
compatibility_date = "2024-10-01"

[env.production]
name = "retain-flow-oauth-prod"

[env.staging]
name = "retain-flow-oauth-staging"

# Environment variables (set via wrangler secret put)
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# DISCORD_CLIENT_ID
# DISCORD_CLIENT_SECRET
# JWT_SECRET
# NEXTAUTH_URL