name = "retain-flow-new"
pages_build_output_dir = ".next"

compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set in Cloudflare dashboard)
[vars]
# These should be set in Cloudflare Pages dashboard, not here
# DATABASE_URL = ""
# JWT_SECRET = ""
# STRIPE_SECRET_KEY = ""
# N8N_API_URL = ""
# COMPOSIO_API_KEY = ""
# POSTHOG_PERSONAL_API_KEY = ""
# CHATWOOT_API_TOKEN = ""
# UNLOCK_PROVIDER_URL = ""

# Optional: KV namespace for caching (uncomment if needed)
# [[kv_namespaces]]
# binding = "INTEGRATIONS_KV"
# id = "your-kv-namespace-id-here"
# preview_id = "your-preview-kv-namespace-id-here"

# Optional: D1 database binding (uncomment if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "retainflow-db"
# database_id = "your-database-id-here"