name = "retainflow-prod"
pages_build_output_dir = "out"

compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace will be created via Cloudflare dashboard
# [[kv_namespaces]]
# binding = "INTEGRATIONS_KV"
# id = "your-kv-namespace-id-here"
# preview_id = "your-preview-kv-namespace-id-here"

[vars]
# PUBLIC_URL = "https://aidevelo.ai"
# JWT_SECRET = "set-in-dashboard"
# DISCORD_CLIENT_ID = "set-in-dashboard"
# DISCORD_CLIENT_SECRET = "set-in-dashboard"
# GOOGLE_CLIENT_ID = "set-in-dashboard"
# GOOGLE_CLIENT_SECRET = "set-in-dashboard"
# STRIPE_SECRET_KEY = "set-in-dashboard"
# STRIPE_WEBHOOK_SECRET = "set-in-dashboard"
# STRIPE_PRICE_ID_PRO = "set-in-dashboard"
# WHOP_WEBHOOK_SECRET = "set-in-dashboard"
# SHOPIFY_CLIENT_ID = "set-in-dashboard"
# SHOPIFY_CLIENT_SECRET = "set-in-dashboard"

